# permissions for end users to edit lxdvirtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lxdvirtualmachine-editor-role
rules:
- apiGroups:
  - components.machinery.canonical
  resources:
  - lxdvirtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.machinery.canonical
  resources:
  - lxdvirtualmachines/status
  verbs:
  - get
