# permissions for end users to view lxdvirtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lxdvirtualmachine-viewer-role
rules:
- apiGroups:
  - components.machinery.canonical
  resources:
  - lxdvirtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - components.machinery.canonical
  resources:
  - lxdvirtualmachines/status
  verbs:
  - get
