---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - components.machinery.canonical
  resources:
  - lxdvirtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.machinery.canonical
  resources:
  - lxdvirtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - components.machinery.canonical
  resources:
  - lxdvirtualmachines/status
  verbs:
  - get
  - patch
  - update
